FROM python:3.13.2-slim

ARG AWS_ACCESS_KEY_ID
ARG AWS_ACCOUNT_ID
ARG AWS_CLOUDWATCH_LOGS_ENDPOINT
ARG AWS_CLOUDWATCH_LOGS_LOG_GROUP
ARG AWS_DEFAULT_REGION
ARG AWS_S3_BUCKET
ARG AWS_S3_ENDPOINT
ARG AWS_SECRET_ACCESS_KEY
ARG AWS_SESSION_TOKEN
ARG CORS_ORIGINS
ARG ENVIRONMENT

ENV AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
ENV AWS_ACCOUNT_ID=${AWS_ACCOUNT_ID}
ENV AWS_CLOUDWATCH_LOGS_ENDPOINT=${AWS_CLOUDWATCH_LOGS_ENDPOINT}
ENV AWS_CLOUDWATCH_LOGS_LOG_GROUP=${AWS_CLOUDWATCH_LOGS_LOG_GROUP}
ENV AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
ENV AWS_S3_BUCKET=${AWS_S3_BUCKET}
ENV AWS_S3_ENDPOINT=${AWS_S3_ENDPOINT}
ENV AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
ENV AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
ENV CORS_ORIGINS=${CORS_ORIGINS}
ENV ENVIRONMENT=${ENVIRONMENT}

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH="${PYTHONPATH}:/source/"

WORKDIR /source/

COPY ./requirements.txt /source/requirements.txt

RUN pip install --no-cache-dir --requirement ./requirements.txt

COPY ./source/ /source/