version: "3.8"

services:
  web:
    build: .
    command: flask run --host=0.0.0.0 --port=5000
    volumes:
      - ./source/:/source/
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
    depends_on:
      - localstack

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=s3
      - DOCKER_HOST=unix:///var/run/docker.sock
