networks:
  bridge:
    driver: bridge

services:
  flask:
    build: .
    command: flask run --host=0.0.0.0 --port=5000 --debug
    networks:
      - bridge
    volumes:
      - ./source/:/source/
    environment:
      FLASK_ENV: development
      FLASK_APP: main
    ports:
      - 5001:5000
    depends_on:
      - localstack

  localstack:
    networks:
      - bridge
    image: localstack/localstack
    environment:
      - SERVICES=s3
      - DOCKER_HOST=unix:///var/run/docker.sock
    ports:
      - 4566:4566
      - 4571:4571
